# This is a basic workflow to help you get started with Actions

name: Deploy libs

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: "yarn.lock"
      - name: Install node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build
        run: yarn build:prod
      - name: Lint
        run: yarn lint
      - name: Tests
        run: yarn test
      - name: Git init
        run: |
          git config --local user.name "TravisCI"
          git config --local user.email "frontend@xcritical.software"
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: "Update version develop"
        if: ${{ !startsWith(github.event.head_commit.message, 'chore(release)') && github.event.ref == 'refs/heads/develop' }}
        run: "yarn version:beta --no-commit-hooks"
      - name: "Update version release"
        if: ${{ !startsWith(github.event.head_commit.message, 'chore(release)') && github.event.ref == 'refs/heads/master' }}
        run: "yarn version:release --no-commit-hooks"
      - name: "Publish develop"
        if: ${{ !startsWith(github.event.head_commit.message, 'chore(release)') && github.event.ref == 'refs/heads/develop' }}
        run: "yarn publish:from-git --canary"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: "Publish release"
        if: ${{ !startsWith(github.event.head_commit.message, 'chore(release)') && github.event.ref == 'refs/heads/master' }}
        run: "yarn publish:from-git "
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git push --follow-tags --no-verify
        if: ${{ !startsWith(github.event.head_commit.message, 'chore(release)') }}
